### ISSUE TITLE
Service install error- "service specific error occurred: 4"

### ISSUE THREAD

**Issue by aand18** [jrossi227/ApacheGUI#38]
Hello! 
How should I debug this?
 
> Installing the service 'ApacheGUI' ...
> Using CATALINA_HOME:    "C:\ApacheGUI-x64-1.11.0\tomcat"
> Using CATALINA_BASE:    "C:\ApacheGUI-x64-1.11.0\tomcat"
> Using JAVA_HOME:        ""
> Using JRE_HOME:         "C:\Program Files\Java\jre-9.0.4"
> Using JVM:              "C:\Program Files\Java\jre-9.0.4\bin\server\jvm.dll"
> The service 'ApacheGUI' has been installed.
> The Apache Tomcat 7 ApacheGUI service is starting.
> The Apache Tomcat 7 ApacheGUI service could not be started.
> 
> A service specific error occurred: 4.
> 
> More help is available by typing NET HELPMSG 3547.

**Comment by aand18** [comment]
It turns out it's a Tomcat bug running with Java 9. Should be fixed as of Tomcat 7.0.82

Error log reads:
> 2018-02-21 12:41:38 Commons Daemon procrun stdout initialized
> -Djava.endorsed.dirs=C:\ApacheGUI-x64-1.11.0\tomcat\endorsed is not supported. Endorsed standards and standalone APIs
> in modular form will be supported via the concept of upgradeable modules.

Dettails here:
[https://stackoverflow.com/questions/45917401/tomcat-7-0-73-doesnt-work-with-java-9/45921092#45921092](https://stackoverflow.com/questions/45917401/tomcat-7-0-73-doesnt-work-with-java-9/45921092#45921092)

**Comment by jrossi227** [comment]
ApacheGUI has not been tested with Java 9. The last tested version is Java 8. When Java 8 was released it also broke the bundled tomcat for Windows and had to be upgraded. I am not surprised that Java 9 has caused the same problem. There are no plans to support Java 9 in the near future.

**Comment by jrossi227** [comment]
Java 9 is supported in 1.12

**Comment by aand18** [comment]
great news, thanks a lot!
