### ISSUE TITLE
../tomcat/bin/startup.sh not found

### ISSUE THREAD

**Issue by DerArchivar** [jrossi227/ApacheGUI#40]
Hello there!

I'm trying to get Apache GUI to run in my HTTPd docker container, but it simply won't start. I always get this error:
```
ash: 0: unknown operand
/opt/ApacheGUI/bin/run.sh: exec: line 6: ../tomcat/bin/startup.sh: not found
```

For reference, here is my complete Dockerfile based on Alpine Linux:
``` bash
FROM httpd:alpine
RUN apk update && apk upgrade

# Install JDK, which is required for Apache GUI
RUN apk add openjdk8

# Install CURL to download Apache GUI
RUN apk add curl

# Set WORKDIR to future home of Apache GUI
WORKDIR /opt/

# Download and unpack Apache GUI
RUN curl -SL https://sourceforge.net/...

# Expose ports for HTTPd
EXPOSE 80 443

# Expose port for Apache GUI
EXPOSE 9999

# Start Apache GUI
ENTRYPOINT /opt/ApacheGUI/bin/run.sh
```

Just to be sure, I even tried building a container on top of Debian Jessie. Here is the Dockerfile:
``` bash
FROM httpd:latest

# Some housekeeping
RUN apt-get -y update
RUN apt-get -y install apt-utils
RUN apt-get -y install curl
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade                      RUN apt-get -y autoremove
RUN apt-get -y autoclean

# Install JDK, which is required for Apache GUI
RUN apt-get -y install default-jdk

# Set WORKDIR to future home of Apache GUI
WORKDIR /opt/

# Download and unpack Apache GUI
RUN curl -SL https://sourceforge.net/...

# Expose ports for HTTPd
EXPOSE 80 443

# Expose port for Apache GUI
EXPOSE 9999

# Start Apache GUI
ENTRYPOINT /opt/ApacheGUI/bin/run.sh
```

If you could give me a solution or at least any hint for this, I'd really be incredibly grateful!

Kind regards

**Comment by jrossi227** [comment]
The script is showing that it can't find the file `../tomcat/bin/startup.sh` which is using a relative path. Your working directory needs to be correct to use a relative path.

Try changing the working directory to `/opt/ApacheGUI/bin/` and then running `run.sh`

Something like this `cd /opt/ApacheGUI/bin/ && run.sh`

**Comment by DerArchivar** [comment]
I totally forgot about this issue, I'm terribly sorry!

You were absolutely right and your feedback helped me resolve the issue(s). Thank you so much for that!
